package topics_backend

const (
	KV_KEY_ALL_VIAL_PROFILES string = "vial-profiles"
	KV_KEY_SYSTEM_VIAL_PROFILES string = "system-vial-profiles"
	PAYLOAD_SMART_SWITCH_OFF string = "OFF"
	PAYLOAD_SMART_SWITCH_ON string = "ON"
	TOPIC_CLOSE_BLIND string = "asol/close_bedroom_blind"
	TOPIC_EMAIL_SEND string = "asol/send-email"
	TOPIC_FRIDGE_SWITCH string = "cmnd/tasmota_sw_fridge/Power1"
	TOPIC_KV_GET string = "asol/kv/get/"
	TOPIC_KV_GET_RESP string = "asol/kv/get-resp/"
	TOPIC_KV_SET string = "asol/kv/set/"
	TOPIC_KV_SET_RESP string = "asol/kv/set-resp/"
	TOPIC_MARK_DELAYED_DISPENSE string = "asol/mark-delayed-dispense"
	TOPIC_MARK_FAILED_DISPENSE string = "asol/mark-failed-dispense"
	TOPIC_MONITOR_OFF string = "asol/monitor_off"
	TOPIC_MONITOR_ON string = "asol/monitor_on"
	TOPIC_OPEN_BLIND string = "asol/open_bedroom_blind"
	TOPIC_PIECE_SELECTED string = "asol/piece-selected"
	TOPIC_SESSION_BEGAN string = "asol/session/began"
	TOPIC_SESSION_BEGIN string = "asol/session/begin"
	TOPIC_SESSION_END string = "asol/session/end"
	TOPIC_SESSION_ENDED string = "asol/session/ended"
	TOPIC_SESSION_PAUSE string = "asol/session/pause"
	TOPIC_SESSION_PAUSED string = "asol/session/paused"
	TOPIC_SESSION_RESUME string = "asol/session/resume"
	TOPIC_SESSION_RESUMED string = "asol/session/resumed"
	TOPIC_SESSION_STATUS_GET string = "asol/session/status-get"
	TOPIC_SESSION_STATUS_RESP_JSON string = "asol/session/status-resp-json"
	TOPIC_SESSION_STATUS_RESP_RAW string = "asol/session/status-resp-raw"
	TOPIC_SMART_SWITCH string = "cmnd/tasmota_sw1/Power1"
	TOPIC_STATE_REPORT_JSON string = "asol/state-report-json"
	TOPIC_STILLS_GENERATED string = "asol/stills-generated"
	TOPIC_STREAM_END string = "asol/stream/end"
	TOPIC_STREAM_START string = "asol/stream/begin"
	TOPIC_STREAM_STATUS_GET string = "asol/stream/status-get"
	TOPIC_STREAM_STATUS_RESP_JSON string = "asol/stream/status-resp-json"
	TOPIC_STREAM_STATUS_RESP_RAW string = "asol/stream/status-resp-raw"
	TOPIC_TRIGGER_DSLR string = "asol/dslr-crop-capture"
	TOPIC_TRIGGER_DSLR_RESP string = "asol/dslr-crop-capture-resp"
	TOPIC_VIDEOS_GENERATED string = "asol/videos-generated"
	TRIGGER_UPLOAD_FROM_LATEST_CONTENT_PLAN string = "asol/upload-from-latest-content-plan"
)
