#!/bin/bash
# generate all video content for session $1
set -e

cd tools
pwd
source .venv/bin/activate

echo "Bash: generating still..."
python3 content_generation_still.py -n $1

echo "Bash: generating shortform..."
python3 content_generation_video.py -y -n $1 -t CONTENT_TYPE_SHORTFORM

echo "Bash: generating cleaning..."
python3 content_generation_video.py -y -n $1 -t CONTENT_TYPE_CLEANING

echo "Bash: generating longform..."
python3 content_generation_video.py -y -n $1 -t CONTENT_TYPE_LONGFORM

echo "Bash: generating timelapse..."
python3 content_generation_timelapse.py -n $1 -d /mnt/md0/light-stores
