package topics_firmware

const (
	IK_Z_LEVEL_MM string = "43"
	TOPIC_COLLECT string = "mega/req/collect"
	TOPIC_DEBUG_DATA string = "mega/req/debug-data"
	TOPIC_DISPENSE string = "mega/req/dispense"
	TOPIC_DISPENSE_RESP string = "mega/resp/dispense"
	TOPIC_FLUID string = "mega/req/fluid"
	TOPIC_GOTO_NODE string = "mega/req/goto-node"
	TOPIC_GOTO_RING_IDLE_POS string = "mega/req/goto-ring-idle-pos"
	TOPIC_GOTO_XY string = "mega/req/goto-xy"
	TOPIC_GOTO_XY_RESP string = "mega/resp/goto-xy"
	TOPIC_LOGS_CRIT string = "mega/l/crit"
	TOPIC_LOGS_DEBUG string = "mega/l/debug"
	TOPIC_LOGS_ERROR string = "mega/l/error"
	TOPIC_LOGS_INFO string = "mega/l/info"
	TOPIC_LOGS_WARN string = "mega/l/warn"
	TOPIC_MAINTENANCE string = "mega/req/maintenance"
	TOPIC_MARK_SAFE_TO_CALIBRATE string = "mega/req/safe-to-calibrate"
	TOPIC_PIN_OFF string = "mega/req/pin-off"
	TOPIC_PIN_ON string = "mega/req/pin-on"
	TOPIC_RINSE string = "mega/req/rinse"
	TOPIC_SET_COVER_CLOSE string = "mega/req/cover-close"
	TOPIC_SET_COVER_OPEN string = "mega/req/cover-open"
	TOPIC_SET_COVER_SERVO_US string = "mega/req/cover-servo-us"
	TOPIC_SET_IK_Z string = "mega/req/set-ik-z"
	TOPIC_SET_VALVE string = "mega/req/set-valve"
	TOPIC_SHUTDOWN string = "mega/req/shutdown"
	TOPIC_SLEEP string = "mega/req/sleep"
	TOPIC_STATE_REPORT_RAW string = "mega/state-report"
	TOPIC_STATE_REPORT_REQUEST string = "mega/req/state-report"
	TOPIC_TOGGLE_MANUAL string = "mega/req/manual"
	TOPIC_UNCALIBRATE string = "mega/req/uncalibrate"
	TOPIC_WAKE string = "mega/req/wake"
)
