/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "machine.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(machine_PipetteState, machine_PipetteState, AUTO)


PB_BIND(machine_CollectionRequest, machine_CollectionRequest, AUTO)


PB_BIND(machine_MovementDetails, machine_MovementDetails, AUTO)


PB_BIND(machine_FluidRequest, machine_FluidRequest, AUTO)


PB_BIND(machine_FluidDetails, machine_FluidDetails, AUTO)


PB_BIND(machine_StateReport, machine_StateReport, AUTO)


PB_BIND(machine_StateReportList, machine_StateReportList, AUTO)


PB_BIND(machine_SessionStatus, machine_SessionStatus, AUTO)


PB_BIND(machine_StreamStatus, machine_StreamStatus, AUTO)


PB_BIND(machine_DispenseMetadataMap, machine_DispenseMetadataMap, AUTO)


PB_BIND(machine_DispenseMetadataMap_DispenseMetadataEntry, machine_DispenseMetadataMap_DispenseMetadataEntry, AUTO)


PB_BIND(machine_DispenseMetadata, machine_DispenseMetadata, AUTO)


PB_BIND(machine_ContentTypeStatuses, machine_ContentTypeStatuses, AUTO)


PB_BIND(machine_ContentTypeStatuses_ContentStatusesEntry, machine_ContentTypeStatuses_ContentStatusesEntry, AUTO)


PB_BIND(machine_ContentTypeStatus, machine_ContentTypeStatus, AUTO)


PB_BIND(machine_Post, machine_Post, AUTO)


PB_BIND(machine_Email, machine_Email, AUTO)


PB_BIND(machine_VialProfile, machine_VialProfile, AUTO)


PB_BIND(machine_SystemVialConfiguration, machine_SystemVialConfiguration, AUTO)


PB_BIND(machine_SystemVialConfiguration_VialsEntry, machine_SystemVialConfiguration_VialsEntry, AUTO)


PB_BIND(machine_VialProfileCollection, machine_VialProfileCollection, AUTO)


PB_BIND(machine_VialProfileCollection_ProfilesEntry, machine_VialProfileCollection_ProfilesEntry, AUTO)


PB_BIND(machine_SystemVialConfigurationSnapshot, machine_SystemVialConfigurationSnapshot, AUTO)


PB_BIND(machine_SystemVialConfigurationSnapshot_ProfilesEntry, machine_SystemVialConfigurationSnapshot_ProfilesEntry, AUTO)












