// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package openapi

import (
	"github.com/gin-gonic/gin"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	Message *string `json:"message,omitempty"`
}

// CollectItemJSONBody defines parameters for CollectItem.
type CollectItemJSONBody struct {
	// Id The ID of the item to collect
	Id *int `json:"id,omitempty"`
}

// GotoPositionJSONBody defines parameters for GotoPosition.
type GotoPositionJSONBody struct {
	// X The x-coordinate to move to
	X *float32 `json:"x,omitempty"`

	// Y The y-coordinate to move to
	Y *float32 `json:"y,omitempty"`
}

// CollectItemJSONRequestBody defines body for CollectItem for application/json ContentType.
type CollectItemJSONRequestBody CollectItemJSONBody

// GotoPositionJSONRequestBody defines body for GotoPosition for application/json ContentType.
type GotoPositionJSONRequestBody GotoPositionJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Collect an item
	// (POST /collect)
	CollectItem(c *gin.Context)
	// Dispense an item
	// (POST /dispense)
	DispenseItem(c *gin.Context)
	// Move the robot to a specific position
	// (POST /goto)
	GotoPosition(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// CollectItem operation middleware
func (siw *ServerInterfaceWrapper) CollectItem(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CollectItem(c)
}

// DispenseItem operation middleware
func (siw *ServerInterfaceWrapper) DispenseItem(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DispenseItem(c)
}

// GotoPosition operation middleware
func (siw *ServerInterfaceWrapper) GotoPosition(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GotoPosition(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/collect", wrapper.CollectItem)
	router.POST(options.BaseURL+"/dispense", wrapper.DispenseItem)
	router.POST(options.BaseURL+"/goto", wrapper.GotoPosition)
}
