#!/bin/bash
# launch the video editing bulk script in a new window

cd ~/asol/software/asol-backend
urxvt -e bash -ic "./scripts/generation/generate-videos $1"
mosquitto_pub -h milkelangelo -t "asol/videos-generated" -m "$1"

