#pragma once

#define E_STOP_PIN 27

#define STEPS_PER_STEPPER_REVOLUTION 200
#define STEPPER_SLEEP 23

#define RING_STEPPER_STEP 22
#define RING_STEPPER_DIR 21
#define Z_STEPPER_STEP 19
#define Z_STEPPER_DIR 18
#define YAW_STEPPER_STEP 5
#define YAW_STEPPER_DIR 17
#define PITCH_STEPPER_STEP 16
#define PITCH_STEPPER_DIR 4
#define PIPETTE_STEPPER_STEP 0
#define PIPETTE_STEPPER_DIR 2

// Limit switches
#define PITCH_LIMIT_SWITCH 33
#define YAW_LIMIT_SWITCH 32
#define Z_LIMIT_SWITCH 35
#define RING_LIMIT_SWITCH 34
#define PIPETTE_LIMIT_SWITCH 25
