#ifndef MQTT_CONSTANTS_H
#define MQTT_CONSTANTS_H

#define IK_Z_LEVEL_MM "45"
#define TOPIC_COLLECT "mega/req/collect"
#define TOPIC_DEBUG_DATA "mega/req/debug-data"
#define TOPIC_DISPENSE "mega/req/dispense"
#define TOPIC_DISPENSE_RESP "mega/resp/dispense"
#define TOPIC_FLUID "mega/req/fluid"
#define TOPIC_GOTO_NODE "mega/req/goto-node"
#define TOPIC_GOTO_RING_IDLE_POS "mega/req/goto-ring-idle-pos"
#define TOPIC_GOTO_XY "mega/req/goto-xy"
#define TOPIC_GOTO_XY_RESP "mega/resp/goto-xy"
#define TOPIC_LOGS_CRIT "mega/l/crit"
#define TOPIC_LOGS_DEBUG "mega/l/debug"
#define TOPIC_LOGS_ERROR "mega/l/error"
#define TOPIC_LOGS_INFO "mega/l/info"
#define TOPIC_LOGS_WARN "mega/l/warn"
#define TOPIC_MAINTENANCE "mega/req/maintenance"
#define TOPIC_MARK_SAFE_TO_CALIBRATE "mega/req/safe-to-calibrate"
#define TOPIC_PIN_OFF "mega/req/pin-off"
#define TOPIC_PIN_ON "mega/req/pin-on"
#define TOPIC_RINSE "mega/req/rinse"
#define TOPIC_SET_COVER_CLOSE "mega/req/cover-close"
#define TOPIC_SET_COVER_OPEN "mega/req/cover-open"
#define TOPIC_SET_COVER_SERVO_US "mega/req/cover-servo-us"
#define TOPIC_SET_IK_Z "mega/req/set-ik-z"
#define TOPIC_SET_VALVE "mega/req/set-valve"
#define TOPIC_SHUTDOWN "mega/req/shutdown"
#define TOPIC_SLEEP "mega/req/sleep"
#define TOPIC_STATE_REPORT_RAW "mega/state-report"
#define TOPIC_STATE_REPORT_REQUEST "mega/req/state-report"
#define TOPIC_TOGGLE_MANUAL "mega/req/manual"
#define TOPIC_UNCALIBRATE "mega/req/uncalibrate"
#define TOPIC_WAKE "mega/req/wake"

#endif // MQTT_CONSTANTS_H
