TOP_CAM = "top-cam"
FRONT_CAM = "front-cam"

# Scenes for defining composition of top and front cams
SCENE_UNDEFINED = "UNDEFINED"
SCENE_FRONT_ONLY = "FRONT_ONLY"
SCENE_DUAL = "DUAL"
SCENE_TOP_ONLY = "TOP_ONLY"

FORMAT_UNDEFINED = "UNDEFINED"
FORMAT_LANDSCAPE = "LANDSCAPE"
FORMAT_PORTRAIT = "PORTRAIT"

TYPE_LONGFORM = "LONGFORM"
TYPE_SHORTFORM = "SHORTFORM"