#!/bin/bash
# Update protos and constants in the relevant directories

set -e

PROTOS_REPO_DIR=./asol-protos
CURRENT_DIR=$(pwd)

cd $PROTOS_REPO_DIR
docker-compose up

echo 'Copying python files'

# PYTHON
cd $CURRENT_DIR
cp -r $PROTOS_REPO_DIR/python/* ./tools/
touch ./tools/topics_backend/__init__.py
touch ./tools/topics_firmware/__init__.py

echo 'Copying typescript files'

# TYPESCRIPT
cd $CURRENT_DIR
cp -r $PROTOS_REPO_DIR/typescript/* ./interface/src/

echo 'Done'
