#!/bin/bash
# This mounts the remote multidisk filesystem, locally.

mkdir -p /mnt/md0/light-stores/
sshfs -o allow_other milkelangelo@milkelangelo:/home/milkelangelo/milk-stores /mnt/md0/light-stores/
