"""
Manually generate / override a session's profile snapshot.
This will usually be generated by goo on session start, from the
list of profiles and system vial configuration.
"""
import os
import argparse
import yaml
import machinepb.machine as pb


def get_args() -> argparse.Namespace:
    """get cli argument"""

    parser = argparse.ArgumentParser()
    parser.add_argument("-d", "--base-dir", action="store",
                        help=("base directory containing session_content and session_metadata"),
                        default="/mnt/md0/light-stores")
    parser.add_argument("-n", "--session-number", action="store",
                        help="session number e.g. 5", required=True)

    return parser.parse_args()


args = get_args()

snapshot = pb.SystemVialConfigurationSnapshot()

dye = pb.VialProfile(
    id=0,
    description="dye",
    footage_delay_ms=0,
    footage_duration_ms=0,
    footage_speed_mult=1,
    footage_ignore=True
)

emulsifier = pb.VialProfile(
    id=1,
    description="emulsifier",
    footage_delay_ms=3000,
    footage_duration_ms=10000,
    footage_speed_mult=5
)

isopropyl = pb.VialProfile(
    id=2,
    description="isopropyl alcohol",
    footage_delay_ms=0,
    footage_duration_ms=2000,
    footage_speed_mult=1
)

snapshot.profiles[1] = dye
snapshot.profiles[2] = dye
snapshot.profiles[3] = isopropyl
snapshot.profiles[4] = emulsifier
snapshot.profiles[5] = dye
snapshot.profiles[6] = dye

OUTPUT = os.path.join(args.base_dir, "session_content", args.session_number, "vial-profiles.yml")
with open(OUTPUT, 'w') as f:
    yaml.dump(
        snapshot.to_dict(include_default_values=True),
        f
    )
